version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-telegram-bot
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - rag-network

  # PostgreSQL (закомментировано до настройки Prisma)
  postgres:
    image: pgvector/pgvector:pg15
    container_name: rag-postgres
    env_file:
      - .env
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - rag-network

volumes:
  postgres_data:

networks:
  rag-network:
    driver: bridge